version: "3.10"
services:
  predictor:
      image: hub.docker.com/darshika/diabetes-predictor:0.0.0
      entrypoint: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
      volumes:
        - .:/app
      ports:
        - 8000:8000
