name: Build and Test

on: [workflow_call]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Check outputs
        run: |
          echo "SHORT_COMMIT=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build
        run: |
          echo "$SHORT_COMMIT"
          echo "${{ env.SHORT_COMMIT }}"
          make build-app VERSION=${{ env.SHORT_COMMIT }}
      - name: Lint check and Test
        run: make build-test VERSION=${{ env.SHORT_COMMIT }}
