name: Feature Branch

on: 
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes master


env:
  PYTHON_VERSION: "3.10"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - call-build-workflow:
        uses: ./.github/workflows/build.yml
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Dockerhub
        run: make push-docker VERSION=${{ env.SHORT_COMMIT }}
      - name: Clean
        run: make clean-docker-base VERSION=${{ env.SHORT_COMMIT }}
