name: Build Test and Publish

on: 
  push:
    pull_requests:
      types: [opened, reopened, ready_for_review]

env:
  PYTHON_VERSION: "3.10"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Check outputs
        run: |
          echo "SHORT_COMMIT=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build
        run: |
          echo "$SHORT_COMMIT"
          echo "${{ env.SHORT_COMMIT }}"
          make build-app VERSION=${{ env.SHORT_COMMIT }}
      - name: Lint and test
        run: make build-test VERSION=${{ env.SHORT_COMMIT }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Push to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: diabetes-predictor
          IMAGE_TAG: ${{ env.SHORT_COMMIT }}
        run: make push-docker VERSION=${{ env.SHORT_COMMIT }}
      - name: Clean
        run: make clean-docker-base VERSION=${{ env.SHORT_COMMIT }} 
