name: Python package

on: [push]

env:
  PYTHON_VERSION: "3.10"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Check outputs
        run: |
          echo "SHOT_COMMIT=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build
        run: |
          echo "$SHOT_COMMIT"
          echo "${{ env.SHOT_COMMIT }}"
          make build-app VERSION=${{ env.SHOT_COMMIT }}
      - name: Test with pytest
        run: make build-test VERSION=${{ env.SHOT_COMMIT }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Dockerhub
        run: make docker-push VERSION=${{ env.SHOT_COMMIT }}
      - name: Clean
        run: make clean-docker-base VERSION=${{ env.SHOT_COMMIT }}
